services:
  gerenciamentodb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Cocozika0202!"
    networks:
      - minha-rede

  gerenciamentotarefas:
    container_name: gerenciamento-tarefas-app
    image: ${DOCKER_REGISTRY-}gerenciamentotarefas
    build:
      context: .
      dockerfile: GerenciamentoTarefas/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - gerenciamentodb
    environment:
      - ASPNETCORE_URLS=http://+:80 
      - DB_HOST=sqlbanco
      - DB_NAME=developDB
      - DB_USER=sqladmin
      - DB_PASSWORD=Cocozika0202!
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
